language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules

## build
script:
  - npm test -- -all --coverage
  - npm run build

## sonar
addons:
  sonarcloud:
    organization: "jsx"
    token: $TOKEN_SONARCLOUD_USER
script:
  # other script steps might be done before running the actual analysis
  - sonar-scanner

## deploy
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  local_dir: ./build
  repo: pedroblanc/pedroblanc.github.io
  target_branch: master
  on:
    branch: master