branches:
  only:
    - master

language: node_js
node_js:
  - "stable"
addons:
  sonarcloud:
    organization: "jsx"
    token: $TOKEN_SONARCLOUD_USER
cache:
  directories:
  - node_modules

test:
  - script: npm test -- --all --coverage
  - script: sonar-scanner

build:
  - script: npm run build

  deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  local_dir: ./build
  repo: pedroblanc/pedroblanc.github.io
  target_branch: master
  on:
    branch: master