branches:
  only:
    - master

language: node_js
node_js:
  - "stable"
addons:
  sonarcloud:
    organization: "jsx"
    token: $TOKEN_SONARCLOUD_USER
cache:
  directories:
  - node_modules

jobs:
  include:
    - stage: test
      script: npm test -- --all --coverage
    - stage: test
      script: sonar-scanner
    - stage: deploy
      before_script: echo "export default '$TRAVIS_COMMIT';" > ./src/commit_number.js
      script: npm run build
      deploy:
        skip_cleanup: true
        cleanup: false
        provider: pages
        github_token: $GITHUB_TOKEN
        keep_history: true
        local_dir: ./build
        repo: pedroblanc/pedroblanc.github.io
        target_branch: master
        on:
          branch: master